fastlane_version "1.98.0"

lane :test_ios14 do
  scan(devices: ["iPhone 12 Pro (14.5)"])
end

lane :test_ios15 do
  scan(devices: ["iPad Pro (12.9-inch) (5th generation) (15.5)"])
end

lane :test_tvos14 do
  scan(device: "Apple TV 4K (14.5)")
end

lane :test_tvos15 do
  scan(device: "Apple TV (15.4)")
end

lane :test_macos do
  scan(destination: "platform=macOS", disable_slide_to_type: false)
end

lane :build_watchos do
  xcodebuild(
    build: true,
    destination: "OS=8.5,name=Apple Watch Series 6 - 44mm",
    scheme: 'TRON'
  )
end

lane :build_watchos_xcode12 do
  xcodebuild(
    build: true,
    destination: "OS=7.4,name=Apple Watch Series 6 - 44mm",
    scheme: 'TRON'
  )
end

lane :pod_lint do
  sh "bundle exec pod repo update"
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :generate_code_coverage do
  slather(
    proj: "TRON.xcodeproj",
    scheme: "TRON",
    # arch: "x86_64",
    verbose: true,
    cobertura_xml: true
  )
end

lane :release do |params|
  version = params[:version]

  abort "You must specify a version in semver format." if version.nil? || version.scan(/\d+\.\d+\.\d+(-\w+\.\d+)?/).length == 0

  puts "Setting Framework version"
  increment_version_number_in_plist(
      version_number: version,
      target: "TRON"
  )

  Dir.chdir("..") do

    puts "Updating podspec."
    filename = "TRON.podspec"
    contents = File.read(filename)
    contents.gsub!(/s\.version\s*=\s"\d+\.\d+\.\d+(-\w+\.\d)?"/, "s.version      = \"#{version}\"")
    File.open(filename, 'w') { |file| file.puts contents }

    puts "Updating changelog."
    changelog_filename = "CHANGELOG.md"
    changelog = File.read(changelog_filename)
    changelog.gsub!(/# Next/, "# Next\n\n## [#{version}](https://github.com/MLSDev/TRON/releases/tag/#{version})")
    File.open(changelog_filename, 'w') { |file| file.puts changelog }

    puts "Comitting, tagging, and pushing."
    message = "Releasing version #{version}."
    sh "git add --all && git commit -m '#{message}'"
    sh "git tag #{version} -m '#{message}'"
    sh "git push --follow-tags"

    puts "Updating Specs repo"
    sh "bundle exec pod repo update"

    puts "Pushing to CocoaPods trunk."
    sh "bundle exec pod trunk push TRON.podspec --allow-warnings"

    puts "Pushing as a GitHub Release."
    fastlane_require 'octokit'
    stripped_changelog = changelog.split(/^## /)[1].split("\n")[1..-1].join("\n").strip
    client = Octokit::Client.new(netrc: true)
    client.create_release('MLSDev/TRON',
                     version,
                     name: version,
                     body: stripped_changelog)
  end
end
